import type { Plan } from "@/types/billing";

export const perVideoPlans: Plan[] = [
  {
    id: "essential-60",
    name: "Essential",
    tagline: "Une vidéo courte et efficace, pour convaincre vite.",
    price: 149,
    currency: "EUR",
    mode: "per_video",
    duration: 60,
    priceEnvKey: "STRIPE_PRICE_60",
    features: [
      "1 vidéo de démonstration de 60 secondes",
      "Export 4K",
      "Script voix off",
      "Sous-titres inclus",
      "Storyboard structuré",
      "1 format au choix",
    ],
  },
  {
    id: "pro-90",
    name: "Pro",
    tagline: "La démonstration standard, complète et équilibrée.",
    price: 249,
    currency: "EUR",
    mode: "per_video",
    duration: 90,
    highlighted: true,
    priceEnvKey: "STRIPE_PRICE_90",
    features: [
      "1 vidéo de démonstration de 90 secondes",
      "Export 4K",
      "Script voix off premium",
      "Sous-titres inclus",
      "Storyboard détaillé",
      "3 formats : 16:9, 9:16, 1:1",
      "1 révision incluse",
    ],
  },
  {
    id: "studio-120",
    name: "Studio",
    tagline: "La démonstration complète, storytelling et kit commercial.",
    price: 399,
    currency: "EUR",
    mode: "per_video",
    duration: 120,
    priceEnvKey: "STRIPE_PRICE_120",
    features: [
      "1 vidéo de démonstration de 120 secondes",
      "Export 4K",
      "Storytelling complet",
      "Script voix off premium",
      "Sous-titres inclus",
      "Storyboard détaillé",
      "3 formats : 16:9, 9:16, 1:1",
      "2 révisions incluses",
      "Kit commercial exportable",
      "Support prioritaire",
    ],
  },
];

export const subscriptionPlans: Plan[] = [
  {
    id: "starter",
    name: "Starter",
    tagline: "Pour publier régulièrement sans y penser.",
    price: 249,
    currency: "EUR",
    mode: "subscription",
    videosPerMonth: 2,
    priceEnvKey: "STRIPE_PRICE_STARTER",
    features: [
      "2 vidéos par mois",
      "Export 4K sur toutes les vidéos",
      "Tous les formats inclus",
      "Sous-titres et scripts",
      "1 marque",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    tagline: "Pour les équipes produit et sales qui itèrent vite.",
    price: 549,
    currency: "EUR",
    mode: "subscription",
    videosPerMonth: 5,
    highlighted: true,
    priceEnvKey: "STRIPE_PRICE_GROWTH",
    features: [
      "5 vidéos par mois",
      "Export 4K sur toutes les vidéos",
      "Tous les formats inclus",
      "Révisions illimitées",
      "3 marques",
      "Bibliothèque de modèles complète",
    ],
  },
  {
    id: "agency",
    name: "Agency",
    tagline: "Pour les agences qui livrent pour plusieurs clients.",
    price: 990,
    currency: "EUR",
    mode: "subscription",
    videosPerMonth: 10,
    priceEnvKey: "STRIPE_PRICE_AGENCY",
    features: [
      "10 vidéos par mois",
      "Export 4K sur toutes les vidéos",
      "Tous les formats inclus",
      "Révisions illimitées",
      "Marques et clients illimités",
      "Mode agence multi-clients",
      "Support prioritaire dédié",
    ],
  },
];

export function findPlan(planId: string): Plan | undefined {
  return [...perVideoPlans, ...subscriptionPlans].find((p) => p.id === planId);
}
